---
- name: Show version from AsterNOS Switch (non-interactive)
  hosts: asterfusion_switches
  gather_facts: no

  tasks:
    - name: Show version (disable paging, add timeout)
      ansible.builtin.raw: |
        timeout 15 sh -lc "printf 'terminal length 0\nshow version\nexit\n' | sonic-cli"
      register: ver_output
      changed_when: false
      failed_when: false
      check_mode: false

    - name: Display show version output
      ansible.builtin.debug:
        msg: "{{ ver_output.stdout | default('NO OUTPUT') | trim }}"
