---
- name: Backup AsterNOS running configuration (config_db.json)
  hosts: asterfusion_switches
  gather_facts: no

  vars:
    backup_dir: "/tmp/asternos_backups"

  tasks:
    - name: Ensure backup directory exists (controller)
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
        mode: "0755"

    - name: Fetch config_db.json from switch
      ansible.builtin.raw: "cat /etc/sonic/config_db.json"
      register: cfg
      changed_when: false
      check_mode: false

    - name: Save config_db.json locally
      ansible.builtin.copy:
        content: "{{ cfg.stdout }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}-config_db.json"
        mode: "0644"

    - name: Confirm
      ansible.builtin.debug:
        msg: "Saved running config to {{ backup_dir }}/{{ inventory_hostname }}-config_db.json"
