---
- name: Show version from AsterNOS Switch
  hosts: asterfusion_switches
  gather_facts: no

  tasks:
    - name: Run show version in sonic-cli
      ansible.builtin.raw: |
        sonic-cli <<'EOF'
        show version
        EOF
      register: ver_output
      changed_when: false
      failed_when: false

    - name: Display show version output
      ansible.builtin.debug:
        msg: "{{ ver_output.stdout | default('NO OUTPUT (command failed or returned nothing)') | trim }}"
