---
- name: Show version from AsterNOS Switch (handles RETURN prompt)
  hosts: asterfusion_switches
  gather_facts: no

  tasks:
    - name: Show version (send RETURN to continue)
      ansible.builtin.raw: |
        timeout 20 sh -lc "printf '\nshow version\n\nexit\n' | sonic-cli"
      register: ver_output
      changed_when: false
      failed_when: false
      check_mode: false

    - name: Display show version output
      ansible.builtin.debug:
        msg: "{{ ver_output.stdout | default('NO OUTPUT') }}"
