---
- name: Get Clock Time from AsterNOS Switch
  hosts: asterfusion_switches
  gather_facts: no

  tasks:
    - name: Execute 'show ver' command using RAW SSH
      # This line is crucial: Must be two spaces of indentation relative to '- name:' above it.
      ansible.builtin.raw: "show ver"
        # This line must be indented exactly four spaces relative to the line above it.

      register: ver_output

    - name: Display the clock time
      ansible.builtin.debug:
        msg: "The ver on {{ inventory_hostname }} is: {{ ver_output.stdout | trim }}"
