- name: Configure VLAN on AsterNOS (raw)
  hosts: asterfusion_switches
  gather_facts: no

  vars:
    vlan_id: 1000
    vlan_name: Finance

  tasks:
    - name: Configure VLAN
      ansible.builtin.raw: |
        sonic-cli <<'EOF'
        configure terminal
        vlan {{ vlan_id }}
        description {{ vlan_name }}
        end
        write
        EOF
