---
- name: Configure VLAN on AsterNOS
  hosts: astronos_switches # Assuming you corrected the spelling here
  gather_facts: no
  connection: network_cli

  vars:
    vlan_id: 1000
    vlan_name: Finance

  tasks:
    - name: Apply VLAN Configuration and Save
      # CRITICAL CHANGE: Use 'config' instead of 'lines'
      ansible.netcommon.cli_config:
        config: |
          configure terminal
          vlan {{ vlan_id }}
          description {{ vlan_name }}
          exit
          end
        
        # This parameter is supported by your module, use it to save
        # save_when: always
