---
- name: Configure VLAN on AsterNOS
  hosts: astronos_switches
  gather_facts: no
  connection: network_cli

  vars:
    vlan_id: 1000
    vlan_name: Finance

  tasks:
    - name: Create VLAN {{ vlan_id }}
      ansible.netcommon.cli_config:
        config: |
          configure terminal
          vlan {{ vlan_id }}
          description {{ vlan_name }}
          end

    - name: Save config (write)
      ansible.netcommon.cli_command:
        command: write
