- name: Configure VLAN on AsterNOS
  hosts: asternos_switches
  gather_facts: no
  connection: network_cli
  vars:
    vlan_id: 1000
    vlan_name: Finance
  tasks:
    - name: Configure VLAN
      ansible.netcommon.cli_config:
        lines:
          - configure terminal
          - vlan {{ vlan_id }}
          - description {{ vlan_name }}
