---
- name: Configure VLAN on AsterNOS
  hosts: asternos_switches
  gather_facts: no
  connection: network_cli

  vars:
    vlan_id: 1000
    vlan_name: Finance

  tasks:
    - name: Create VLAN {{ vlan_id }}
      ansible.netcommon.cli_config:
        lines:
          - vlan {{ vlan_id }}
          - description {{ vlan_name }}
        parents: []
        save_when: never

    - name: Save configuration
      ansible.netcommon.cli_command:
        command: write
