- name: Enter CLI and Apply VLAN Configuration
      # Replace 'aster-cli' with the actual command you discovered!
      ansible.builtin.raw: |
        aster-cli
        configure terminal
        vlan 1000
        description Test
        end
        write memory
